[config]
skip_core_tasks = true
default_to_workspace = false

[env]
REPOSITORY_ROOT = { script = [ "git rev-parse --show-superproject-working-tree --show-toplevel" ] }

[tasks.test]
script_runner = "@shell"
script = [
    "cd build",
    "make",
    "make test",
]
