name: Full Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ubuntu:
    runs-on: ${{ matrix.compiler.os }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cxx: clang++
            ver: 17
            os: ubuntu-24.04
          - cxx: clang++
            ver: 18
            os: ubuntu-24.04
          - cxx: clang++
            ver: 19
            os: ubuntu-24.04
          - cxx: g++
            ver: 13
            os: ubuntu-24.04
          - cxx: g++
            ver: 14
            os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y -qq pkg-config cmake

      - name: Install Clang
        if: startsWith(matrix.compiler.cxx, 'clang')
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.compiler.ver }}

      - name: Install GCC
        if: matrix.compiler.cxx == 'g++' && matrix.compiler.ver == 14
        run: sudo apt update && sudo apt install -y gcc-14

      - name: Cache Catch2
        id: cache
        uses: actions/cache@v4
        with:
          path: $VCPKG_INSTALLATION_ROOT/installed
          key: ${{ runner.os }}-

      - name: Install Catch2
        if: steps.cache.outputs.cache-hit != 'true'
        run: vcpkg install catch2

      - name: Build and test
        run: |
          cmake -S . -B build \
            -DBUILD_TESTING=ON \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}-${{ matrix.compiler.ver }} \
            -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
          cmake --build build
          cd build && ctest

  windows:
    runs-on: windows-${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - vs: "Visual Studio 17 2022"
            os: 2025
          - vs: "Visual Studio 17 2022"
            os: 2022
    steps:
      - uses: actions/checkout@v4

      - name: Cache Catch2
        id: cache
        uses: actions/cache@v4
        with:
          path: $VCPKG_INSTALLATION_ROOT/installed
          key: ${{ runner.os }}-

      - name: Install Catch2
        if: steps.cache.outputs.cache-hit != 'true'
        run: vcpkg install catch2

      - name: Build and test
        run: |
          cmake -S . -B build `
            -G "${{ matrix.config.vs }}" -A x64 `
            -DBUILD_TESTING=ON `
            -DCMAKE_TOOLCHAIN_FILE="$($env:VCPKG_INSTALLATION_ROOT)/scripts/buildsystems/vcpkg.cmake"
          cmake --build build
          cd build && ctest

  macos:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        cxx: ["clang++", "$(brew --prefix llvm@18)/bin/clang++"]
    steps:
      - uses: actions/checkout@v4

      - name: Cache Catch2
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/vcpkg/installed
          key: ${{ runner.os }}-

      - name: Install vcpkg
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ~
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          ./bootstrap-vcpkg.sh
          ./vcpkg install catch2

      - name: Build and test
        run: |
          cmake -S . -B build \
            -DBUILD_TESTING=ON \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_TOOLCHAIN_FILE="~/vcpkg/scripts/buildsystems/vcpkg.cmake"
          cmake --build build
          cd build && ctest
